name: 'Halfday Env Scanner'
description: 'Scan .env files for leaked API keys, weak passwords, and security issues'
branding:
  icon: 'shield'
  color: 'green'

inputs:
  path:
    description: 'Path to the .env file to scan'
    required: false
    default: '.env.example'
  fail-grade:
    description: 'Minimum passing grade (A-F). Grades below this fail the step.'
    required: false
    default: 'D'
  comment-on-pr:
    description: 'Post findings as a PR comment'
    required: false
    default: 'true'
  halfday-token:
    description: 'Halfday Pro token (reserved for future use)'
    required: false
    default: ''
  config:
    description: 'Path to .halfday.yml config (reserved for future use)'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Run Halfday Env Scanner
      shell: bash
      run: bash ${{ github.action_path }}/entrypoint.sh
      env:
        INPUT_PATH: ${{ inputs.path }}
        INPUT_FAIL_GRADE: ${{ inputs.fail-grade }}
        INPUT_COMMENT_ON_PR: ${{ inputs.comment-on-pr }}
        GITHUB_TOKEN: ${{ github.token }}
